[2025-02-17T22:16:21.192-0700] {processor.py:157} INFO - Started process (PID=148724) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:16:21.193-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:16:21.194-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:16:21.194-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:16:21.199-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:16:21.198-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:16:21.200-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:16:21.200-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:16:21.200-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:16:21.215-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-17T22:17:15.410-0700] {processor.py:157} INFO - Started process (PID=148960) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:17:15.411-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:17:15.412-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:17:15.411-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:17:15.416-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:17:15.415-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:17:15.416-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:17:15.416-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:17:15.417-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:17:15.426-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-17T22:18:05.760-0700] {processor.py:157} INFO - Started process (PID=149460) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:18:05.762-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:18:05.763-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:18:05.763-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:18:05.766-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:18:05.765-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:18:05.766-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:18:05.766-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:18:05.766-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:18:05.775-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-02-17T22:19:03.770-0700] {processor.py:157} INFO - Started process (PID=149999) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:19:03.773-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:19:03.775-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:19:03.774-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:19:03.781-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:19:03.779-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:19:03.781-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:19:03.781-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:19:03.781-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:19:03.797-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-17T22:20:02.645-0700] {processor.py:157} INFO - Started process (PID=150552) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:20:02.648-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:20:02.649-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:20:02.648-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:20:02.654-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:20:02.653-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:20:02.655-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:20:02.655-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:20:02.655-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:20:02.669-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-17T22:21:00.481-0700] {processor.py:157} INFO - Started process (PID=151100) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:00.482-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:21:00.484-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:00.483-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:00.491-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:00.489-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:21:00.491-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:00.491-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:21:00.491-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:00.507-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-17T22:21:51.179-0700] {processor.py:157} INFO - Started process (PID=151573) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:51.182-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:21:51.183-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:51.182-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:51.188-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:51.187-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:21:51.189-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:21:51.188-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:21:51.189-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:21:51.203-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-17T22:22:44.519-0700] {processor.py:157} INFO - Started process (PID=151781) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:22:44.522-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:22:44.523-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:22:44.523-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:22:44.528-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:22:44.527-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:22:44.529-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:22:44.528-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:22:44.529-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:22:44.548-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-17T22:23:37.508-0700] {processor.py:157} INFO - Started process (PID=152244) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:23:37.511-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:23:37.512-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:23:37.511-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:23:37.517-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:23:37.516-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:23:37.517-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:23:37.517-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:23:37.517-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:23:37.532-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-17T22:24:32.824-0700] {processor.py:157} INFO - Started process (PID=152784) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:24:32.826-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:24:32.827-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:24:32.827-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:24:32.832-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:24:32.831-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:24:32.832-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:24:32.832-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:24:32.833-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:24:32.848-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-17T22:25:29.890-0700] {processor.py:157} INFO - Started process (PID=153313) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:25:29.893-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:25:29.894-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:25:29.894-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:25:29.899-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:25:29.898-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:25:29.899-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:25:29.899-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:25:29.900-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:25:29.914-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-02-17T22:26:28.072-0700] {processor.py:157} INFO - Started process (PID=153855) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:26:28.075-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:26:28.077-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:26:28.076-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:26:28.081-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:26:28.080-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:26:28.081-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:26:28.081-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:26:28.082-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:26:28.096-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-17T22:27:19.351-0700] {processor.py:157} INFO - Started process (PID=154365) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:27:19.353-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:27:19.355-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:27:19.354-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:27:19.363-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:27:19.361-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:27:19.363-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:27:19.363-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:27:19.364-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:27:19.391-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-02-17T22:28:16.434-0700] {processor.py:157} INFO - Started process (PID=154877) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:28:16.436-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:28:16.438-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:28:16.437-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:28:16.446-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:28:16.444-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:28:16.446-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:28:16.446-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:28:16.446-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:28:16.465-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-17T22:29:17.143-0700] {processor.py:157} INFO - Started process (PID=155290) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:29:17.146-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:29:17.148-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:29:17.148-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:29:17.154-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:29:17.152-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:29:17.154-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:29:17.154-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:29:17.154-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:29:17.169-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-17T22:30:17.299-0700] {processor.py:157} INFO - Started process (PID=155589) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:30:17.302-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:30:17.303-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:30:17.302-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:30:17.307-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:30:17.305-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:30:17.307-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:30:17.307-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:30:17.308-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:30:17.317-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-02-17T22:31:10.765-0700] {processor.py:157} INFO - Started process (PID=156114) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:31:10.766-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:31:10.770-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:31:10.768-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:31:10.775-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:31:10.774-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:31:10.775-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:31:10.775-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:31:10.775-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:31:10.787-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-02-17T22:32:05.823-0700] {processor.py:157} INFO - Started process (PID=156661) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:05.826-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:32:05.827-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:32:05.827-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:05.833-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:32:05.832-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:32:05.833-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:32:05.833-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:32:05.834-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:05.847-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-17T22:33:04.074-0700] {processor.py:157} INFO - Started process (PID=157066) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:04.076-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:33:04.076-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:33:04.076-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:04.081-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:33:04.080-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:33:04.081-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:33:04.081-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:33:04.082-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:04.094-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-02-17T22:34:02.094-0700] {processor.py:157} INFO - Started process (PID=157558) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:02.096-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:34:02.097-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:02.097-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:02.103-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:02.102-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:34:02.104-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:02.103-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:34:02.104-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:02.119-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-17T22:34:55.801-0700] {processor.py:157} INFO - Started process (PID=157960) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:55.804-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:34:55.806-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:55.805-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:55.812-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:55.810-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:34:55.812-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:34:55.812-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:34:55.812-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:55.826-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-17T22:35:52.049-0700] {processor.py:157} INFO - Started process (PID=158484) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:35:52.052-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:35:52.053-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:35:52.052-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:35:52.058-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:35:52.057-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:35:52.059-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:35:52.059-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:35:52.059-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:35:52.073-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-17T22:36:54.457-0700] {processor.py:157} INFO - Started process (PID=159050) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:54.459-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:36:54.460-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:36:54.460-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:54.467-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:36:54.466-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:36:54.467-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:36:54.467-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:36:54.467-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:54.481-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-17T22:37:48.178-0700] {processor.py:157} INFO - Started process (PID=160024) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:48.181-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:37:48.182-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:37:48.182-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:48.188-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:37:48.187-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:37:48.188-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:37:48.188-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:37:48.189-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:48.203-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-17T22:38:40.222-0700] {processor.py:157} INFO - Started process (PID=160663) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:40.225-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:38:40.225-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:38:40.225-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:40.229-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:38:40.228-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:38:40.229-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:38:40.229-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:38:40.230-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:40.239-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-17T22:39:34.307-0700] {processor.py:157} INFO - Started process (PID=161216) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:34.309-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:39:34.309-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:39:34.309-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:34.313-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:39:34.312-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:39:34.313-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:39:34.313-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:39:34.313-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:34.321-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-02-17T22:40:31.391-0700] {processor.py:157} INFO - Started process (PID=161692) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:40:31.393-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:40:31.394-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:40:31.393-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:40:31.400-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:40:31.398-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:40:31.400-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:40:31.400-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:40:31.400-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:40:31.412-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-02-17T22:41:29.887-0700] {processor.py:157} INFO - Started process (PID=162194) to work on /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:29.889-0700] {processor.py:829} INFO - Processing file /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:41:29.890-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:41:29.890-0700] {dagbag.py:536} INFO - Filling up the DagBag from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:29.895-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:41:29.894-0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:41:29.896-0700] {logging_mixin.py:154} INFO - [2025-02-17T22:41:29.896-0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:41:29.896-0700] {processor.py:841} WARNING - No viable dags retrieved from /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:29.912-0700] {processor.py:179} INFO - Processing /home/jparep/miniconda3/envs/dbt-env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
